package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type GlassEntry struct {
	ND float64 `yaml:"nd"`
	VD float64 `yaml:"vd"`
}

type GlassDataset struct {
	Glasses []GlassEntry `yaml:"glasses"`
}

type Point2D struct{ ND, VD float64 }

func main() {
	// Read YAML data
	yamlPath := filepath.Join("GLASS", "glass_nd_vd_data.yaml")
	data, err := os.ReadFile(yamlPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error reading %s: %v\n", yamlPath, err)
		os.Exit(1)
	}
	var dataset GlassDataset
	if err := yaml.Unmarshal(data, &dataset); err != nil {
		fmt.Fprintf(os.Stderr, "error parsing %s: %v\n", yamlPath, err)
		os.Exit(1)
	}

	pts := make([]Point2D, len(dataset.Glasses))
	ndMin, ndMax := 1e9, -1e9
	vdMin, vdMax := 1e9, -1e9
	for i, g := range dataset.Glasses {
		pts[i] = Point2D{g.ND, g.VD}
		if g.ND < ndMin {
			ndMin = g.ND
		}
		if g.ND > ndMax {
			ndMax = g.ND
		}
		if g.VD < vdMin {
			vdMin = g.VD
		}
		if g.VD > vdMax {
			vdMax = g.VD
		}
	}

	// Build convex hull using Andrew's monotone chain
	hull := convexHull(pts)

	// Generate Go source
	var b strings.Builder
	b.WriteString("package glass\n\n")
	b.WriteString("// Auto-generated by cmd/hullgen. DO NOT EDIT.\n")
	b.WriteString("// Re-generate: go run ./cmd/hullgen/\n\n")

	fmt.Fprintf(&b, "var DefaultHullVertices = []Point2D{\n")
	for _, p := range hull {
		fmt.Fprintf(&b, "\t{%.8f, %.6f},\n", p.ND, p.VD)
	}
	b.WriteString("}\n\n")

	fmt.Fprintf(&b, "const DefaultHullNDMin = %.8f\n", ndMin)
	fmt.Fprintf(&b, "const DefaultHullNDMax = %.8f\n", ndMax)
	fmt.Fprintf(&b, "const DefaultHullVDMin = %.8f\n", vdMin)
	fmt.Fprintf(&b, "const DefaultHullVDMax = %.8f\n", vdMax)

	b.WriteString("\nfunc NewDefaultConvexHull() *ConvexHull {\n")
	b.WriteString("\treturn NewConvexHull(DefaultHullVertices, DefaultHullNDMin, DefaultHullNDMax, DefaultHullVDMin, DefaultHullVDMax)\n")
	b.WriteString("}\n")

	outPath := filepath.Join("internal", "glass", "hull_data.go")
	if err := os.WriteFile(outPath, []byte(b.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing %s: %v\n", outPath, err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s: %d hull vertices from %d points\n", outPath, len(hull), len(pts))
	fmt.Printf("ND range: [%.6f, %.6f], VD range: [%.6f, %.6f]\n", ndMin, ndMax, vdMin, vdMax)
}

func convexHull(points []Point2D) []Point2D {
	// Sort: ND ascending, VD ascending as tiebreaker
	sort.Slice(points, func(i, j int) bool {
		if points[i].ND != points[j].ND {
			return points[i].ND < points[j].ND
		}
		return points[i].VD < points[j].VD
	})
	// Remove duplicates
	unique := []Point2D{points[0]}
	for i := 1; i < len(points); i++ {
		if points[i].ND != points[i-1].ND || points[i].VD != points[i-1].VD {
			unique = append(unique, points[i])
		}
	}
	if len(unique) <= 1 {
		return unique
	}

	cross := func(o, a, b Point2D) float64 {
		return (a.ND-o.ND)*(b.VD-o.VD) - (a.VD-o.VD)*(b.ND-o.ND)
	}

	lower := make([]Point2D, 0, len(unique)/2)
	for _, p := range unique {
		for len(lower) >= 2 && cross(lower[len(lower)-2], lower[len(lower)-1], p) <= 0 {
			lower = lower[:len(lower)-1]
		}
		lower = append(lower, p)
	}

	upper := make([]Point2D, 0, len(unique)/2)
	for i := len(unique) - 1; i >= 0; i-- {
		p := unique[i]
		for len(upper) >= 2 && cross(upper[len(upper)-2], upper[len(upper)-1], p) <= 0 {
			upper = upper[:len(upper)-1]
		}
		upper = append(upper, p)
	}

	// Remove last point of each list (it's repeated as first of the other)
	return append(lower[:len(lower)-1], upper[:len(upper)-1]...)
}
