package glass

// Auto-generated by cmd/hullgen. DO NOT EDIT.
// Re-generate: go run ./cmd/hullgen/

var DefaultHullVertices = []Point2D{
	{1.41268000, 100.700000},
	{1.45844000, 67.830000},
	{1.46450200, 65.767612},
	{1.51118000, 50.900000},
	{1.57583000, 35.200000},
	{1.62423000, 30.050000},
	{1.66382000, 27.346974},
	{1.86966000, 20.020000},
	{1.98612000, 16.480000},
	{2.10194900, 16.785097},
	{2.15400000, 17.200000},
	{2.10200000, 23.390000},
	{1.41390000, 101.000000},
}

const DefaultHullNDMin = 1.41268000
const DefaultHullNDMax = 2.15400000
const DefaultHullVDMin = 16.48000000
const DefaultHullVDMax = 101.00000000

func NewDefaultConvexHull() *ConvexHull {
	return NewConvexHull(DefaultHullVertices, DefaultHullNDMin, DefaultHullNDMax, DefaultHullVDMin, DefaultHullVDMax)
}
