version: 1
glass_catalog:
  entries:
  - type: model
    label: BK7
    nd: 1.5168
    vd: 64.1673
  - type: model
    label: F2
    nd: 1.62004
    vd: 36.37
optimization:
  method: dls
  max_iter: 100
  tol: 1.0e-06
  epsilon: 1.0e-06
  aperture_margin: 1.2
  shared_variables:
  - name: s1_curvature
    min: -0.2
    max: 0.2
    active: true
    bindings:
    - config: config0
      id: 1
      param: curvature
    - config: config1
      id: 1
      param: curvature
    - config: config2
      id: 1
      param: curvature
  - name: s2_curvature
    min: -0.2
    max: 0.2
    active: true
    bindings:
    - config: config0
      id: 2
      param: curvature
    - config: config1
      id: 2
      param: curvature
    - config: config2
      id: 2
      param: curvature
  - name: s4_curvature
    min: -0.2
    max: 0.2
    active: true
    bindings:
    - config: config0
      id: 4
      param: curvature
    - config: config1
      id: 4
      param: curvature
    - config: config2
      id: 4
      param: curvature
  - name: s5_curvature
    min: -0.2
    max: 0.2
    active: true
    bindings:
    - config: config0
      id: 5
      param: curvature
    - config: config1
      id: 5
      param: curvature
    - config: config2
      id: 5
      param: curvature
  - name: s7_curvature
    min: -0.2
    max: 0.2
    active: true
    bindings:
    - config: config0
      id: 7
      param: curvature
    - config: config1
      id: 7
      param: curvature
    - config: config2
      id: 7
      param: curvature
  - name: s8_curvature
    min: -0.2
    max: 0.2
    active: true
    bindings:
    - config: config0
      id: 8
      param: curvature
    - config: config1
      id: 8
      param: curvature
    - config: config2
      id: 8
      param: curvature
  - name: s10_curvature
    min: -0.2
    max: 0.2
    active: true
    bindings:
    - config: config0
      id: 10
      param: curvature
    - config: config1
      id: 10
      param: curvature
    - config: config2
      id: 10
      param: curvature
  - name: s11_curvature
    min: -0.2
    max: 0.2
    active: true
    bindings:
    - config: config0
      id: 11
      param: curvature
    - config: config1
      id: 11
      param: curvature
    - config: config2
      id: 11
      param: curvature
  - name: s1_thickness
    min: 0.1
    max: 30.0
    active: true
    bindings:
    - config: config0
      id: 1
      param: thickness
    - config: config1
      id: 1
      param: thickness
    - config: config2
      id: 1
      param: thickness
  - name: s4_thickness
    min: 0.1
    max: 30.0
    active: true
    bindings:
    - config: config0
      id: 4
      param: thickness
    - config: config1
      id: 4
      param: thickness
    - config: config2
      id: 4
      param: thickness
  - name: s7_thickness
    min: 0.1
    max: 30.0
    active: true
    bindings:
    - config: config0
      id: 7
      param: thickness
    - config: config1
      id: 7
      param: thickness
    - config: config2
      id: 7
      param: thickness
  - name: s10_thickness
    min: 0.1
    max: 30.0
    active: true
    bindings:
    - config: config0
      id: 10
      param: thickness
    - config: config1
      id: 10
      param: thickness
    - config: config2
      id: 10
      param: thickness
  - name: s1_diameter
    min: 5.0
    max: 100.0
    active: true
    bindings:
    - config: config0
      id: 1
      param: diameter
    - config: config1
      id: 1
      param: diameter
    - config: config2
      id: 1
      param: diameter
  - name: s2_diameter
    min: 5.0
    max: 100.0
    active: true
    bindings:
    - config: config0
      id: 2
      param: diameter
    - config: config1
      id: 2
      param: diameter
    - config: config2
      id: 2
      param: diameter
  - name: s3_diameter
    min: 5.0
    max: 100.0
    active: true
    bindings:
    - config: config0
      id: 3
      param: diameter
    - config: config1
      id: 3
      param: diameter
    - config: config2
      id: 3
      param: diameter
  - name: s4_diameter
    min: 5.0
    max: 100.0
    active: true
    bindings:
    - config: config0
      id: 4
      param: diameter
    - config: config1
      id: 4
      param: diameter
    - config: config2
      id: 4
      param: diameter
  - name: s5_diameter
    min: 5.0
    max: 100.0
    active: true
    bindings:
    - config: config0
      id: 5
      param: diameter
    - config: config1
      id: 5
      param: diameter
    - config: config2
      id: 5
      param: diameter
  - name: s6_diameter
    min: 5.0
    max: 100.0
    active: true
    bindings:
    - config: config0
      id: 6
      param: diameter
    - config: config1
      id: 6
      param: diameter
    - config: config2
      id: 6
      param: diameter
  - name: s7_diameter
    min: 5.0
    max: 100.0
    active: true
    bindings:
    - config: config0
      id: 7
      param: diameter
    - config: config1
      id: 7
      param: diameter
    - config: config2
      id: 7
      param: diameter
  - name: s8_diameter
    min: 5.0
    max: 100.0
    active: true
    bindings:
    - config: config0
      id: 8
      param: diameter
    - config: config1
      id: 8
      param: diameter
    - config: config2
      id: 8
      param: diameter
  - name: s9_diameter
    min: 5.0
    max: 100.0
    active: true
    bindings:
    - config: config0
      id: 9
      param: diameter
    - config: config1
      id: 9
      param: diameter
    - config: config2
      id: 9
      param: diameter
  - name: s10_diameter
    min: 5.0
    max: 100.0
    active: true
    bindings:
    - config: config0
      id: 10
      param: diameter
    - config: config1
      id: 10
      param: diameter
    - config: config2
      id: 10
      param: diameter
  - name: s11_diameter
    min: 5.0
    max: 100.0
    active: true
    bindings:
    - config: config0
      id: 11
      param: diameter
    - config: config1
      id: 11
      param: diameter
    - config: config2
      id: 11
      param: diameter
  - name: s12_diameter
    min: 5.0
    max: 100.0
    active: true
    bindings:
    - config: config0
      id: 12
      param: diameter
    - config: config1
      id: 12
      param: diameter
    - config: config2
      id: 12
      param: diameter
  local_variables:
  - name: config0_gap1
    config: config0
    target:
      type: surface
      id: 3
      param: thickness
    min: 0.1
    max: 200.0
    active: true
  - name: config0_gap2
    config: config0
    target:
      type: surface
      id: 6
      param: thickness
    min: 0.1
    max: 200.0
    active: true
  - name: config0_gap3
    config: config0
    target:
      type: surface
      id: 9
      param: thickness
    min: 0.1
    max: 200.0
    active: true
  - name: config0_bf
    config: config0
    target:
      type: surface
      id: 11
      param: thickness
    min: 0.1
    max: 200.0
    active: true
  - name: config1_gap1
    config: config1
    target:
      type: surface
      id: 3
      param: thickness
    min: 0.1
    max: 200.0
    active: true
  - name: config1_gap2
    config: config1
    target:
      type: surface
      id: 6
      param: thickness
    min: 0.1
    max: 200.0
    active: true
  - name: config1_gap3
    config: config1
    target:
      type: surface
      id: 9
      param: thickness
    min: 0.1
    max: 200.0
    active: true
  - name: config1_bf
    config: config1
    target:
      type: surface
      id: 11
      param: thickness
    min: 0.1
    max: 200.0
    active: true
  - name: config2_gap1
    config: config2
    target:
      type: surface
      id: 3
      param: thickness
    min: 0.1
    max: 200.0
    active: true
  - name: config2_gap2
    config: config2
    target:
      type: surface
      id: 6
      param: thickness
    min: 0.1
    max: 200.0
    active: true
  - name: config2_gap3
    config: config2
    target:
      type: surface
      id: 9
      param: thickness
    min: 0.1
    max: 200.0
    active: true
  - name: config2_bf
    config: config2
    target:
      type: surface
      id: 11
      param: thickness
    min: 0.1
    max: 200.0
    active: true
  constraints: []
chief:
  reference_surface: 12
  num_rays: 256
  grid_type: hex
  dump_map: true
  fields:
  - image_height: 0.0
  - image_height: 10.0
  - image_height: 15.0
configs:
- id: config0
  name: Wide
  weight: 1.0
  active: true
  fields:
  - id: 0
    image_height: 0.0
    weight: 1.0
  - id: 1
    image_height: 10.0
    weight: 1.0
  - id: 2
    image_height: 15.0
    weight: 1.0
  wavelengths:
  - id: 0
    value: 0.00058756
    weight: 1.0
  ray_paths:
  - object_surface: 0
    image_surface: 12
    stop_surface: 4
  surfaces:
  - id: 1
    type: sphere
    curvature: 0.008
    thickness: 10.0
    material: BK7
    diameter: 20.0
  - id: 2
    type: sphere
    curvature: -0.01
    thickness: 0.0
    material: AIR
    diameter: 40.0
  - id: 3
    type: sphere
    curvature: 0.0
    thickness: 20.0
    material: AIR
    diameter: 40.0
  - id: 4
    type: sphere
    curvature: -0.01
    thickness: 10.0
    material: F2
    diameter: 40.0
  - id: 5
    type: sphere
    curvature: 0.01
    thickness: 0.0
    material: AIR
    diameter: 40.0
  - id: 6
    type: sphere
    curvature: 0.0
    thickness: 50.0
    material: AIR
    diameter: 40.0
  - id: 7
    type: sphere
    curvature: 0.01
    thickness: 10.0
    material: BK7
    diameter: 40.0
  - id: 8
    type: sphere
    curvature: -0.01
    thickness: 0.0
    material: AIR
    diameter: 40.0
  - id: 9
    type: sphere
    curvature: 0.0
    thickness: 20.0
    material: AIR
    diameter: 40.0
  - id: 10
    type: sphere
    curvature: 0.01
    thickness: 10.0
    material: BK7
    diameter: 40.0
  - id: 11
    type: sphere
    curvature: -0.01
    thickness: 40.0
    material: AIR
    diameter: 40.0
  - id: 12
    type: sphere
    curvature: 0.0
    thickness: 0.0
    material: AIR
    diameter: 40.0
  merit:
    type: spot_rms
    terms:
    - kind: spot_rms
      field: 0
      wavelength: 0.00058756
      weight: 5.0
    - kind: spot_rms
      field: 1
      wavelength: 0.00058756
      weight: 1.0
    - kind: spot_rms
      field: 2
      wavelength: 0.00058756
      weight: 0.5
  constraints:
  - kind: band
    measure: abs_efl
    lower: 60
    upper: 100
    weight: 1.0
    active: true
  - kind: inequality_lower
    measure: edge_thickness
    surface: 1
    lower: 1.0
    weight: 1.0
    active: true
    surface2: 2
  - kind: inequality_lower
    measure: edge_thickness
    surface: 4
    lower: 1.0
    weight: 1.0
    active: true
    surface2: 5
  - kind: inequality_lower
    measure: edge_thickness
    surface: 7
    lower: 1.0
    weight: 1.0
    active: true
    surface2: 8
  - kind: inequality_lower
    measure: edge_thickness
    surface: 10
    lower: 1.0
    weight: 1.0
    active: true
    surface2: 11
  - kind: equality
    measure: entrance_pupil_diameter
    target: 20
    weight: 1.0
    active: true
  - kind: inequality_lower
    measure: vignetting_factor
    field: 1
    lower: 0.5
    weight: 10.0
    active: true
  - kind: inequality_lower
    measure: vignetting_factor
    field: 2
    lower: 0.5
    weight: 10.0
    active: true
- id: config1
  name: Mid
  weight: 1.0
  active: true
  fields:
  - id: 0
    image_height: 0.0
    weight: 1.0
  - id: 1
    image_height: 10.0
    weight: 1.0
  - id: 2
    image_height: 15.0
    weight: 1.0
  wavelengths:
  - id: 0
    value: 0.00058756
    weight: 1.0
  ray_paths:
  - object_surface: 0
    image_surface: 12
    stop_surface: 4
  surfaces:
  - id: 1
    type: sphere
    curvature: 0.008
    thickness: 10.0
    material: BK7
    diameter: 20.0
  - id: 2
    type: sphere
    curvature: -0.01
    thickness: 0.0
    material: AIR
    diameter: 40.0
  - id: 3
    type: sphere
    curvature: 0.0
    thickness: 40.0
    material: AIR
    diameter: 40.0
  - id: 4
    type: sphere
    curvature: -0.01
    thickness: 10.0
    material: F2
    diameter: 40.0
  - id: 5
    type: sphere
    curvature: 0.01
    thickness: 0.0
    material: AIR
    diameter: 40.0
  - id: 6
    type: sphere
    curvature: 0.0
    thickness: 30.0
    material: AIR
    diameter: 40.0
  - id: 7
    type: sphere
    curvature: 0.01
    thickness: 10.0
    material: BK7
    diameter: 40.0
  - id: 8
    type: sphere
    curvature: -0.01
    thickness: 0.0
    material: AIR
    diameter: 40.0
  - id: 9
    type: sphere
    curvature: 0.0
    thickness: 20.0
    material: AIR
    diameter: 40.0
  - id: 10
    type: sphere
    curvature: 0.01
    thickness: 10.0
    material: BK7
    diameter: 40.0
  - id: 11
    type: sphere
    curvature: -0.01
    thickness: 40.0
    material: AIR
    diameter: 40.0
  - id: 12
    type: sphere
    curvature: 0.0
    thickness: 0.0
    material: AIR
    diameter: 40.0
  merit:
    type: spot_rms
    terms:
    - kind: spot_rms
      field: 0
      wavelength: 0.00058756
      weight: 5.0
    - kind: spot_rms
      field: 1
      wavelength: 0.00058756
      weight: 1.0
    - kind: spot_rms
      field: 2
      wavelength: 0.00058756
      weight: 0.5
  constraints:
  - kind: band
    measure: abs_efl
    lower: 90
    upper: 130
    weight: 1.0
    active: true
  - kind: inequality_lower
    measure: edge_thickness
    surface: 1
    lower: 1.0
    weight: 1.0
    active: true
    surface2: 2
  - kind: inequality_lower
    measure: edge_thickness
    surface: 4
    lower: 1.0
    weight: 1.0
    active: true
    surface2: 5
  - kind: inequality_lower
    measure: edge_thickness
    surface: 7
    lower: 1.0
    weight: 1.0
    active: true
    surface2: 8
  - kind: inequality_lower
    measure: edge_thickness
    surface: 10
    lower: 1.0
    weight: 1.0
    active: true
    surface2: 11
  - kind: equality
    measure: entrance_pupil_diameter
    target: 20
    weight: 1.0
    active: true
  - kind: inequality_lower
    measure: vignetting_factor
    field: 1
    lower: 0.5
    weight: 10.0
    active: true
  - kind: inequality_lower
    measure: vignetting_factor
    field: 2
    lower: 0.5
    weight: 10.0
    active: true
- id: config2
  name: Tele
  weight: 1.0
  active: true
  fields:
  - id: 0
    image_height: 0.0
    weight: 1.0
  - id: 1
    image_height: 10.0
    weight: 1.0
  - id: 2
    image_height: 15.0
    weight: 1.0
  wavelengths:
  - id: 0
    value: 0.00058756
    weight: 1.0
  ray_paths:
  - object_surface: 0
    image_surface: 12
    stop_surface: 4
  surfaces:
  - id: 1
    type: sphere
    curvature: 0.008
    thickness: 10.0
    material: BK7
    diameter: 20.0
  - id: 2
    type: sphere
    curvature: -0.01
    thickness: 0.0
    material: AIR
    diameter: 40.0
  - id: 3
    type: sphere
    curvature: 0.0
    thickness: 60.0
    material: AIR
    diameter: 40.0
  - id: 4
    type: sphere
    curvature: -0.01
    thickness: 10.0
    material: F2
    diameter: 40.0
  - id: 5
    type: sphere
    curvature: 0.01
    thickness: 0.0
    material: AIR
    diameter: 40.0
  - id: 6
    type: sphere
    curvature: 0.0
    thickness: 10.0
    material: AIR
    diameter: 40.0
  - id: 7
    type: sphere
    curvature: 0.01
    thickness: 10.0
    material: BK7
    diameter: 40.0
  - id: 8
    type: sphere
    curvature: -0.01
    thickness: 0.0
    material: AIR
    diameter: 40.0
  - id: 9
    type: sphere
    curvature: 0.0
    thickness: 20.0
    material: AIR
    diameter: 40.0
  - id: 10
    type: sphere
    curvature: 0.01
    thickness: 10.0
    material: BK7
    diameter: 40.0
  - id: 11
    type: sphere
    curvature: -0.01
    thickness: 40.0
    material: AIR
    diameter: 40.0
  - id: 12
    type: sphere
    curvature: 0.0
    thickness: 0.0
    material: AIR
    diameter: 40.0
  merit:
    type: spot_rms
    terms:
    - kind: spot_rms
      field: 0
      wavelength: 0.00058756
      weight: 5.0
    - kind: spot_rms
      field: 1
      wavelength: 0.00058756
      weight: 1.0
    - kind: spot_rms
      field: 2
      wavelength: 0.00058756
      weight: 0.5
  constraints:
  - kind: band
    measure: abs_efl
    lower: 100
    upper: 200
    weight: 1.0
    active: true
  - kind: inequality_lower
    measure: edge_thickness
    surface: 1
    lower: 1.0
    weight: 1.0
    active: true
    surface2: 2
  - kind: inequality_lower
    measure: edge_thickness
    surface: 4
    lower: 1.0
    weight: 1.0
    active: true
    surface2: 5
  - kind: inequality_lower
    measure: edge_thickness
    surface: 7
    lower: 1.0
    weight: 1.0
    active: true
    surface2: 8
  - kind: inequality_lower
    measure: edge_thickness
    surface: 10
    lower: 1.0
    weight: 1.0
    active: true
    surface2: 11
  - kind: equality
    measure: entrance_pupil_diameter
    target: 20
    weight: 1.0
    active: true
  - kind: inequality_lower
    measure: vignetting_factor
    field: 1
    lower: 0.5
    weight: 10.0
    active: true
  - kind: inequality_lower
    measure: vignetting_factor
    field: 2
    lower: 0.5
    weight: 10.0
    active: true
